version: 2
updates:
  # Keep NuGet packages up to date across the repo
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "Europe/Amsterdam"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "nuget"
    # Group small dependency bumps together to reduce PR noise (optional)
    groups:
      minor-and-patch:
        update-types:
          - "minor"
          - "patch"

  # Keep GitHub Actions up to date
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Europe/Amsterdam"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "github-actions"
